var questions=[
	{type:"qcu",question:"Que connait l`économie mondiale en 1924",reponses:["Une phase de croissance","Une phase de décroissance","Une phase constante"],br:"Une phase de croissance"},
	{type:"qcu",question:"Quel est le pays qui a une phase de prospérité spectaculaire à partir de 1924 ?",reponses:["La Chine","Les USA","L`Allemagne"],br:"Les USA"},
	{type:"qcu",question:"Quelle est la cause du Krach Boursier de 1929 ?",reponses:["Les banques ne voulaient pas preter","Il y avait un fort chomage","Les banques pretaient beaucoup"],br:"Les banques pretaient beaucoup"},
	{type:"dat",question:"Quand a eu lieu le Krach Boursier ?",reponses:[1914,1945],br:["octobre","1929"]},
	{type:"qcu",question:"Qu`est-ce qu`entraine le Krach Boursier ?",reponses:["Une grande dépression","Les banques veulent preter plus","Une entraide entre les pays"],br:"Une grande dépression"},
	{type:"qcu",question:"Quelle est l`ampleur de la crise économique suite au Krach Boursier ?",reponses:["Régionale","Nationale","Continentale","Mondiale"],br:"Mondiale"},
	{type:"qcu",question:"Il y a une crise économique mondiale car ?",reponses:["Les USA investissent plus","Les USA investissent moins","Les USA retirent leurs investissements"],br:"Les USA retirent leurs investissements"},
	{type:"dat",question:"Quand est-ce que l`Allemagne devient l`un des pays les plus touchés par la crise ?",reponses:[1914,1945],br:["1930"]},
	{type:"qcu",question:"Comment se passe la crise pour les pays exportateurs de matières premiere ?",reponses:["Ils s`en sortent bien","Cela augmente leurs exportations","Ils sont durement touchés"],br:"Ils sont durement touchés"},
	{type:"qcu",question:"Comment réagissent les gouvernements au début de la crise ?",reponses:["Ils menent des politiques de déflation","Ils menent des politiques d`inflation","Ils ne font rien"],br:"Ils menent des politiques de déflation"},
	{type:"qcu",question:"Quels sont les conséquences des politiques de déflation ?",reponses:["Elles apauvrissent la population","Elles enrichissent la population","Elles n`ont aucuns résultats"],br:"Elles apauvrissent la population"},
	{type:"qcu",question:"Que n`a pas dit H.Hoover ?",reponses:["Les Américains sont aujourd`hui plus près qu`aucune autre nation de vaincre la pauvreté","Mon objectif, c`est un poulet dans chaque casserole, et une voiture dans chaque garage","Venez, achetez, empruntez, c`est gratuit !"],br:"Venez, achetez, empruntez, c`est gratuit !"},
	{type:"dat",question:"Quelle etait la date des élections opposant H.Hoover à FD Roosvelt ?",reponses:[1914,1945],br:["1932"]},
	{type:"qcu",question:"Qui a remporté les elections de 1932 ?",reponses:["Franklin Delano Roosvelt","Herbert Hoover","Calvin Coolidge"],br:"Franklin Delano Roosvelt"},
	{type:"qcu",question:"Que propose FD Roosvelt lors de son premier mandat ?",reponses:["The New Deal","The Last Deal","The Best Deal"],br:"The New Deal"},
	{type:"qcu",question:"Est-ce que FD Roosvelt met en place de Grands Travaux ?",reponses:["Oui","Non"],br:"Oui"},
	{type:"qcu",question:"Pour FD Roosvelt, qu`est-ce qu`une politique moderne ?",reponses:["Une politique de déflation","Une politique de persécution","Une politique d`importation","Une politique de communication"],br:"Une politique de communication"},
	{type:"qcu",question:"Que deviennent les USA grâce à FD Roosvelt ?",reponses:["Un Etat Laïque","Un Etat Exeptionnel","Un Etat Providence","Un Etat Capitaliste"],br:"Un Etat Providence"},
	{type:"qcu",question:"Quel est le bilan du New Deal ?",reponses:["Une agravation de la crise mais une amélioration du moral de la population","Une amélioration de la crise mais une diminution du moral de la population","Un bilan mitigé mais une amélioration du moral de la population","Un bilan exceptionnel et une amélioration du moral de la population"],br:"Un bilan mitigé mais une amélioration du moral de la population"},
	{type:"qcu",question:"Quel était le gouvernement en France après la 1ere guerre mondiale ?",reponses:["La 2nd République","La 3eme République","La 4eme République"],br:"La 3eme République"},
	{type:"dat",question:"Quand est-ce que la France est touchés par la crise ?",reponses:[1914,1945],br:["1932"]},
	{type:"dat",question:"Quand est-ce qu`il y a de fortes manifestations politiques à Paris ?",reponses:[1914,1945],br:["6","fevrier","1934"]},
	{type:"qcu",question:"Qui n`était pas dans le Front Populaire lors de sa formation ?",reponses:["Les radicaux","Les socialistes","Les communistes","Les antisocialistes"],br:"Les antisocialistes"},
	{type:"qcu",question:"Qui devient le président du conseil en février 1934 ?",reponses:["Léon Blum","Edouard Daladier","Maurice Taurez"],br:"Léon Blum"},
	{type:"qcu",question:"Quelle était l`une des mesures phares des accords de Matigon ?",reponses:["3 semaines de congés payés par ans","Le droit de grève","La semaine à 40 heures de travail"],br:"La semaine à 40 heures de travail"},
	{type:"qcu",question:"Est-ce que le Front Populaire reste longtemps au pouvoir ?",reponses:["Oui","Non"],br:"Non"},
	{type:"dat",question:"Quand a eu lieu la premiere révolution des Bolchéviques en Russie ?",reponses:[1914,1945],br:["fevrier","1917"]},
	{type:"dat",question:"Quand a eu lieu la seconde révolution des Bolchéviques en Russie ?",reponses:[1914,1945],br:["octobre","1917"]},
	{type:"qcu",question:"Qui était à la tete des Bolchéviques au début ?",reponses:["Lénine","Staline","Trotski"],br:"Lénine"},
	{type:"dat",question:"Quand se fini la guerre civile débutée par les révolutions de 1917 ?",reponses:[1914,1945],br:["1921"]},
	{type:"qcu",question:"Comment les Bolchéviques prennent le pouvoir ?",reponses:["Par un coup d`Etat","En gagnant des éléctions","L`ancient gouvernement leurs a laissé la place gentillement"],br:"Par un coup d`Etat"},
	{type:"qcu",question:"Est-ce qu`après 1917, le parti Communiste est le seul parti autorisé en Russie ?",reponses:["Oui","Non"],br:"Oui"},
	{type:"qcu",question:"Quelle est la police politique créée en Russie le 20 décembre 1918 ?",reponses:["La Guestapo","Les Koulaks","La Tchéka"],br:"La Tchéka"},
	{type:"dat",question:"Quand a été créée la Tchéka ?",reponses:[1914,1945],br:["decembre","1918"]},
	{type:"qcu",question:"Comment appelle t`on les camps d`internement et de concentration en Russie/URSS ?",reponses:["Les Ghettos","Les Koulaks","Les Goulags"],br:"Les Goulags"},
	{type:"dat",question:"Quand est-ce que la Russie devient l`URSS ?",reponses:[1914,1945],br:["1922"]},
	{type:"qcu",question:"Quelle était la situation de la Russie en 1921 ?",reponses:["Pays Riche","Pays Modeste","Pays Ruiné"],br:"Pays Ruiné"},
	{type:"qcu",question:"Pourquoi est-ce que Lénine ne met pas tout de suite le communisme en place ?",reponses:["Car la Russie était ruiné","Car il y avait trop d`opposition","Car trop de pression des pays voisins"],br:"Car la Russie était ruiné"},
	{type:"qcu",question:"Quelle politique est-ce que Lénine met en place pour sauver l`économie de la Russie/URSS ?",reponses:["Le Communisme","La collectivisation des terres","La Nouvelle Politique Economique (NEP)"],br:"La Nouvelle Politique Economique (NEP)"},
	{type:"qcu",question:"En quoi consistait la NEP ?",reponses:["Interdire les entreprises privées car elles réduisent l`économie nationale","Garder les entreprises privées pour retablir l`économie","Privatiser tous les secteurs afin que les entreprises fassent le plus de profit possible"],br:"Garder les entreprises privées pour retablir l`économie"},
	{type:"qcu",question:"Qui succède à Lénine ?",reponses:["Poutine","Trotski","Staline"],br:"Staline"},
	{type:"dat",question:"Quand meurt Lénine ?",reponses:[1914,1945],br:["1924"]},
	{type:"qcu",question:"Qui succède à Lénine ?",reponses:["Poutine","Trotski","Staline"],br:"Staline"},
	{type:"qcu",question:"Que fait Staline dès qu`il entre au pouvoir ?",reponses:["Il déclare la guerre à l`Allemagne","Il créée l`URSS","Il met fin à la NEP"],br:"Il met fin à la NEP"},
	{type:"qcu",question:"Quelle est la mesure fondatrice du Communisme de Staline ?",reponses:["La collectivitisation des terres","L`appauvrissement de la population","La Nouvelle Politique Economique"],br:"La collectivitisation des terres"},
	{type:"qcu",question:"Comment s`appellent les exploitations collectives agricoles en URSS ?",reponses:["Les Kolkhozes","Les Artels","Les Sovkhozes"],br:"Les Kolkhozes"},
	{type:"qcu",question:"Quel est le but de la collectivitisation des terres en URSS ?",reponses:["Appauvrir la population","Réduire les inégalités","Industrialiser l`agriculture"],br:"Industrialiser l`agriculture"},
	{type:"qcu",question:"Est-ce que la majorités des paysans étaient partisans de la collectivisation des terres ?",reponses:["Oui","Non"],br:"Non"},
	{type:"qcu",question:"Comment s`appellent les paysans opposés à la collectivisation des terres ?",reponses:["Les Kolkhozes","Les Koulaks","Les Solvkhozes"],br:"Les Koulaks"},
	{type:"dat",question:"Quand y a t`il une grande famine en URSS ?",reponses:[1914,1945],br:["1933"]},
	{type:"qcu",question:"Comment s`appelle la nouvelle police politique de Staline de 1934?",reponses:["Le NKVD","La Guestapo","La Tchéka","La Guérpéon"],br:"Le NKVD"},
	{type:"dat",question:"Quand est mise en place le NKVD ?",reponses:[1914,1945],br:["decembre","1934"]},
	{type:"qcu",question:"Quels est le prétexte de la grande terreur en URSS ?",reponses:["Les activités antisoviétiques","L`industrialisation de l`URSS","La pauvreté de la population"],br:"Les activités antisoviétiques"},
	{type:"qcu",question:"Qu`est-ce que le procès de Moscou ?",reponses:["Un procès contre les juifs","Les vieux Bolchéviques avouent leurs fautes et sont fusillés","Staline qui s`escuse des excès du NKVD"],br:"Les vieux Bolchéviques avouent leurs fautes et sont fusillés"},
	{type:"qcu",question:"Pourquoi l`Italie n`est pas contente après la 1ere guerre mondiale ?",reponses:["Ils ont des réparations à payer","Il y a une puissante crise économique","Elle n`a pas pu récupérer des territoires d`Autriche-Hongrie"],br:"Elle n`a pas pu récupérer des territoires d`Autriche-Hongrie"},
	{type:"qcu",question:"Que se passe t'il en Italie après la 1ere guerre mondiale ?",reponses:["Il y a de violentes manifestations paysannes et ouvrières","Il y a de violentes manifestations bourgoises"],br:"Il y a de violentes manifestations paysannes et ouvrières"},
	{type:"dat",question:"Quand est-ce que le roi Italien nomme Mussolini Président du Conseil ?",reponses:[1914,1945],br:["30","octobre","1922"]},
	{type:"dat",question:"Quand est-ce que Mussolini fait voter les lois fascitissimes ?",reponses:[1914,1945],br:["1925"]},
	{type:"dat",question:"Quand est-ce que l'Italie se raproche de l'Allemagne  ?",reponses:[1914,1945],br:["1936"]},
	{type:"dat",question:"Quand est-ce que la France impose le traité de Versailles aux Allemands ?",reponses:[1914,1945],br:["28","juin","1919"]},
	{type:"dat",question:"Quand est-ce que l'Allemagne va rentrer dans la Société des nations ?",reponses:[1914,1945],br:["1925"]},
	{type:"dat",question:"Quand est-ce qu'Hitler échoue lamentablement dans une tentative de coup d'Etat ?",reponses:[1914,1945],br:["1923"]},
	{type:"dat",question:"Quand est-ce qu'Hitler devient chancelier ?",reponses:[1914,1945],br:["30","janvier","1933"]},
	{type:"dat",question:"Quand est-ce qu'a eu lieu la nuit de cristal ?",reponses:[1914,1945],br:["9","novembre","1938"]},
	{type:"dat",question:"Quand est-ce qu'Hitler rétablit le service militaire ?",reponses:[1914,1945],br:["1935"]},
	{type:"dat",question:"Quand est-ce qu'Hitler remilitarise la Rhémanie ?",reponses:[1914,1945],br:["mars","1936"]},
	{type:"dat",question:"Quand a eu lieu la guerre civile en Espagne ?",reponses:[1914,1945],br:["1936"]},
	{type:"dat",question:"Quand est-ce qu'Hitler annexe l'Autriche ?",reponses:[1914,1945],br:["mars","1938"]},
	{type:"dat",question:"Quand a eu lieu la conférence de Munich ?",reponses:[1914,1945],br:["30","septembre","1938"]},
	{type:"dat",question:"Quand commence la 2nd guerre mondiale ?",reponses:[1914,1945],br:["1","septembre","1939"]},
]