var q={type:"",question:"",reponses:[],br:0},

var questions=[
    {type:"qcu",question:"Où ne se situent pas les Métropoles Francaises ?",reponses:["Aux littoraux","Près des frontières","À la montagne","Dans les vallées fluviales"],br:"À la montagne"},
    {type:"qcu",question:"Quelles sont les zones les plus dynamiques en France ?",reponses:["À l'Ouest et au Sud","Au Nord et L'Est","Au centre et au Nord"],br:"À l'Ouest et au Sud"},
    {type:"inp",question:"Définition de PIB",reponses:[],br:"Somme des richesses produites dans un pays et en une année donnée"},
    {type:"inp",question:"Définition de Pays Emergent",reponses:[],br:"pays en développement qui pourraient etre un jour développés."},
    {type:"qcu",question:"A partir de combien est ce qu'un pays a un taux de croissance économique élevé ?",reponses:["+ 5% du PIB/an","+ 10% du PIB/an","+ 15% du PIB/an"],br:"+ 5% du PIB/an"},
    {type:"inp",question:"Définition de BRICS",reponses:[],br:"Les puissances émergentes : Brésil, Russie, Inde, Chine, Afrique du Sud."},
    {type:"qcu",question:"Combien y a t'il de PMA dans le monde ?",reponses:["36 pays","47 pays","53 pays"],br:"47 pays"},
    {type:"inp",question:"Définition de Métropole",reponses:[],br:"Ville qui exerce une domination sur un espace donné"},
    {type:"qcu",question:"Combien de personnes vivent dans une ville aujourd'hui ?",reponses:["75%","45%","55%"],br:"55%"},
    {type:"inp",question:"Définition de Mégapole",reponses:[],br:"Ville de plus de 10 millions d'habitants"},
    {type:"qcu",question:"Quelle est la capitale de diamant et la banque centrale indienne aujourd'hui ?",reponses:["New Dehli","Mumbaï","Kolkata ( Calcutta )"],br:"Mumbaï"},
    {type:"inp",question:"Définition de Métropolisation",reponses:[],br:"Processus de concentration des centres de commandement dans les grandes villes"},
    {type:"inp",question:"Définition de Mondialisation",reponses:[],br:"Mise en relation économique des différents espaces de la planète"},
    {type:"inp",question:"Définition de Archipel Métropolitain Mondial",reponses:[],br:"Réseau des grandes métropoles reliées entre elles"},
    {type:"inp",question:"Définition de Mégalopole",reponses:[],br:"Espace urbanisé contenant plusieurs grandes villes reliées entre elles"},
    {type:"inp",question:"Définition de Gentrification",reponses:[],br:"Embourgeoisement des centres villes"},
    {type:"inp",question:"Définition de Gated Community",reponses:[],br:"Quartiers fermés surveillés par des vigiles pour populations aisées"},
    {type:"qcu",question:"Quelle est la Mégalopole Américaine ?",reponses:["la SANMIA(San Antonio-Dallas-Houston-New Orleans-Tampa-Miami)","la CHAMIA (Charlotte-Atlanta-Tampa-Miami)","la BOSWASH(Boston-New York-Philadelphie-Baltimore-Washington)"],br:"la BOSWASH(Boston-New York-Philadelphie-Baltimore-Washington)"},
    {type:"qcu",question:"Est-ce que Paris fait partie de la Mégalopole Européenne ?",reponses:["Oui","Non"],br:"Non"},
    {type:"qcu",question:"Quelle est la capitale boursière des USA ?",reponses:["New-York","Washington","Los Angeles"],br:"New-York"},
    {type:"qcu",question:"Est-ce que la CITY de Londre est le 1er centre économique mondial ?",reponses:["Oui","Non"],br:"Oui"},
    {type:"qcu",question:"Combien il y a t-il d'habitants dans l'agglomérations Parisienne?",reponses:["10 millions","12 millions","15 millions"],br:"12 millions"},
    {type:"qcu",question:"La France est un État ....... ?",reponses:["Centralisé","Décentralisé"],br:"Centralisé"},
]