var questions=[
	{type:"dat",question:"Quand est-ce qu'il y a eu la révolution de février à Paris ?",reponses:[1800,1890],br:["fevrier","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la création du droit du travail ?",reponses:[1800,1890],br:["25","fevrier","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu l'abolition de la peine de mort ?",reponses:[1800,1890],br:["26","fevrier","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la création des Ateliers Nationaux ?",reponses:[1800,1890],br:["26","fevrier","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la loi sur la limitation de la journée de travail ?",reponses:[1800,1890],br:["2","mars","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la liberté totale de presse et de réunion ?",reponses:[1800,1890],br:["4","mars","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu le suffrage universel masculin ?",reponses:[1800,1890],br:["5","mars","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu l'abolition de l'esclavage ?",reponses:[1800,1890],br:["27","avril","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la suppression des ateliers nationaux ?",reponses:[1800,1890],br:["22","juin","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu le début des révoltes ouvrières ?",reponses:[1800,1890],br:["22","juin","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la fin des révoltes ouvrières ?",reponses:[1800,1890],br:["26","juin","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu le coup d'Etat ( Napoléon devient Président ) ?",reponses:[1800,1890],br:["2","décembre","1848"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la loi de sureté générale ?",reponses:[1800,1890],br:["1858"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu le passage de la 2nd république au 2nd Empire ?",reponses:[1800,1890],br:["2","décembre","1852"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la liberté de la presse ?",reponses:[1800,1890],br:["1867"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu l'autorisation de réunion publique tant que ce n'était pas politique ?",reponses:[1800,1890],br:["1868"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu le début de l'industrialisation en France (environ) ?",reponses:[1800,1890],br:["1830"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu une première exposition universelle à Paris ?",reponses:[1800,1890],br:["1855"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu une seconde exposition universelle à Paris ? ",reponses:[1800,1890],br:["1867"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu la guerre de CRIMÉE ( le début ) ?",reponses:[1800,1890],br:["1854"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu l'expédition au Mexique ( le début ) ? ",reponses:[1800,1890],br:["1862"]},
	{type:"dat",question:"Quand est-ce qu'il y a eu l'alliance franco-piémontaise ?",reponses:[1800,1890],br:["1858"]},
	{type:"dat",question:"Quand est-ce que Victor Emmanuel 2 est devenu le roi d'Italie ? ",reponses:[1800,1890],br:["1861"]},
]