var questions=[
	{type:"qcu",question:"Quand nait l'Assemblée Nationale ?",reponses:["le 16 juin 1789","le 17 juin 1789","le 18 juin 1789"],br:"le 17 juin 1789"},
	{type:"qcu",question:"Qui est a la tete de la Terreur ?",reponses:["Rosbespierre","Louis XIV","Louis XVI"],br:"Rosbespierre"},
	{type:"qcu",question:"Qui veut le vote par tête et non par ordre aux Etats-Generaux ?",reponses:["La noblesse","le tiers-etat","le clergé"],br:"le tiers-etat"},
	{type:"qcu",question:"Pourquoi les nobles ont peur lors de la Grande Peur",reponses:["le roi devient de plus en plus méchant","Les Anglais veulent leurs déclarer la guerre","Les paysans les attaquent dans la campagne"],br:"Les paysans les attaquent dans la campagne"},
	{type:"qcu",question:"Que fait le decret d'Allarde ?",reponses:["Il donne plus de libertés aux entrepreneurs","Il autorise les corporations","Il autorise la greve et les syndicats"],br:"Il donne plus de libertés aux entrepreneurs"},
	{type:"qcu",question:"Qui se trouve à gauche de l'Assemblée nationale ?",reponses:["Les révolutionnaires qui veulent arreter la révolution","le roi","les revolutionnaires qui veulent continuer la revolution","Les revolutionnaires neutres"],br:"les revolutionnaires qui veulent continuer la revolution"},
	{type:"qcu",question:"Quelle est la seconde Assemblée Nationale ?",reponses:["la Constituante","la Convention","La Legislative"],br:"La Legislative"},
	{type:"qcu",question:"Où est-ce que retrouvent des personnes ayant une opinion politique commune ?",reponses:["Dans un club politique","A l'Assemblée Nationale","Chez le roi"],br:"Dans un club politique"},
	{type:"qcu",question:"Dans quel camp se trouve La Fayette ?",reponses:["Aux Montagnards","Aux Girondins","Au clubs des Feuillant"],br:"Au clubs des Feuillant"},
	{type:"qcu",question:"Dans quel camp se trouve Robespierre ?",reponses:["Aux Montagnards","Aux Girondins","Au clubs des Feuillant"],br:"Aux Montagnards"},
	{type:"qcu",question:"Completez cette expression : Avec la Constitution de 1791, la Nation est ......",reponses:["royale","souveraine","riche"],br:"souveraine"},
	{type:"qcu",question:"Quels sont les pouvoirs du rois dans la monarchie Constitutionelle ?",reponses:["le pouvoir éxécutif","le pouvoir législatif","le pouvoir judiciaire"],br:"le pouvoir éxécutif"},
	{type:"qcu",question:"Quand est-ce que Manon Roland meurt ?",reponses:["le 10 juin 1794","le 11 juin 1793","le 1 juin 1793"],br:"le 1 juin 1793"},
	{type:"qcu",question:"Que se passe t-il en juillet 1794",reponses:["Le calendrier révolutionnaire a été mis en place","Robespierre se fait guillotiner","il y a l'abolition de l'esclavage"],br:"Robespierre se fait guillotiner"},
	{type:"qcu",question:"Quel est le nom du gouvernement de 1795-1799 ?",reponses:["le Directeur","le Directoire","la Direction"],br:"le Directoire"},
	{type:"dat",question:"Quand Louis XVI meurt-il ?",reponses:[1785,1815],br:["21","janvier","1793"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la fête de la fédération ?",reponses:[1785,1815],br:["14","juillet","1790"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la DDHC ?",reponses:[1785,1815],br:["26","aout","1789"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la prise de la Bastille ?",reponses:[1785,1815],br:["14","juillet","1789"]},
	{type:"dat",question:"Quand est ce qu'il y a eu l'abolition des privilèges ?",reponses:[1785,1815],br:["4","aout","1789"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la prise des tuileries (chute de la monarchie) ?",reponses:[1785,1815],br:["10","aout","1792"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la proclamation de la République ?",reponses:[1785,1815],br:["22","septembre","1792"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la chute de Robespierre ?",reponses:[1785,1815],br:["27","juillet","1794"]},
	{type:"dat",question:"Quand est ce qu'il y a eu le coup d'état de Napoléon Bonaparte ?",reponses:[1785,1815],br:["9","novembre","1799"]},
	{type:"dat",question:"Quand est ce qu'il y a eu le serment du jeu de paume ?",reponses:[1785,1815],br:["20","juin","1789"]},
	{type:"dat",question:"Quand est ce que Napoleon Bonaparte a été sacré empereur ?",reponses:[1785,1815],br:["2","decembre","1804"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la défaite de Waterloo ?",reponses:[1785,1815],br:["18","juin","1815"]},
	{type:"dat",question:"Quand est ce que les deputes du ters etat se proclament Assemblée Nationale ?",reponses:[1785,1815],br:["17","juin","1789"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la fuite du roi ?",reponses:[1785,1815],br:["20","juin","1791"]},
	{type:"dat",question:"Quand est ce qu'il y a eu la défaite de Waterloo ?",reponses:[1785,1815],br:["18","septembre","1793"]},
]